export const activityLabelMessageKeys = new Map([
  ["Archive imported", "activityLabelArchiveImported"],
  ["Blacklist rule added", "activityLabelBlacklistRuleAdded"],
  ["Chrome URLs and vault records deleted", "activityLabelChromeUrlsAndVaultRecordsDeleted"],
  ["Current Chrome URLs and vault records deleted", "activityLabelCurrentChromeUrlsAndVaultRecordsDeleted"],
  ["Current results CSV exported", "activityLabelCurrentResultsCsvExported"],
  ["Current results deleted", "activityLabelCurrentResultsDeleted"],
  ["Current results HTML exported", "activityLabelCurrentResultsHtmlExported"],
  ["Current results JSON exported", "activityLabelCurrentResultsJsonExported"],
  ["Domain rule removed", "activityLabelDomainRuleRemoved"],
  ["Domains blacklisted", "activityLabelDomainsBlacklisted"],
  ["Duplicate cleanup", "activityLabelDuplicateCleanup"],
  ["Full CSV exported", "activityLabelFullCsvExported"],
  ["Full HTML exported", "activityLabelFullHtmlExported"],
  ["JSON backup exported", "activityLabelJsonBackupExported"],
  ["Local vault reset", "activityLabelLocalVaultReset"],
  ["Retention cleanup", "activityLabelRetentionCleanup"],
  ["Selected CSV exported", "activityLabelSelectedCsvExported"],
  ["Selected HTML exported", "activityLabelSelectedHtmlExported"],
  ["Selected JSON exported", "activityLabelSelectedJsonExported"],
  ["Vault delete undone", "activityLabelVaultDeleteUndone"],
  ["Vault records deleted", "activityLabelVaultRecordsDeleted"],
  ["Whitelist rule added", "activityLabelWhitelistRuleAdded"],
  ["blacklist rule added", "activityLabelBlacklistRuleAdded"],
  ["category rule added", "activityLabelCategoryRuleAdded"],
  ["whitelist rule added", "activityLabelWhitelistRuleAdded"]
]);

export const activityTypeMessageKeys = new Map([
  ["backup", "activityTypeBackup"],
  ["cleanup", "activityTypeCleanup"],
  ["delete", "activityTypeDelete"],
  ["export", "activityTypeExport"],
  ["import", "activityTypeImport"],
  ["reset", "activityTypeReset"],
  ["restore", "activityTypeRestore"],
  ["rule", "activityTypeRule"]
]);

export const activityLogLocalization = [
  { key: "activityFallbackLabel" },
  { key: "activityLabelArchiveImported" },
  { key: "activityLabelBlacklistRuleAdded" },
  { key: "activityLabelCategoryRuleAdded" },
  { key: "activityLabelChromeUrlsAndVaultRecordsDeleted" },
  { key: "activityLabelCurrentChromeUrlsAndVaultRecordsDeleted" },
  { key: "activityLabelCurrentResultsCsvExported" },
  { key: "activityLabelCurrentResultsDeleted" },
  { key: "activityLabelCurrentResultsHtmlExported" },
  { key: "activityLabelCurrentResultsJsonExported" },
  { key: "activityLabelDomainRuleRemoved" },
  { key: "activityLabelDomainsBlacklisted" },
  { key: "activityLabelDuplicateCleanup" },
  { key: "activityLabelFullCsvExported" },
  { key: "activityLabelFullHtmlExported" },
  { key: "activityLabelJsonBackupExported" },
  { key: "activityLabelLocalVaultReset" },
  { key: "activityLabelRetentionCleanup" },
  { key: "activityLabelSelectedCsvExported" },
  { key: "activityLabelSelectedHtmlExported" },
  { key: "activityLabelSelectedJsonExported" },
  { key: "activityLabelVaultDeleteUndone" },
  { key: "activityLabelVaultRecordsDeleted" },
  { key: "activityLabelWhitelistRuleAdded" },
  { key: "activityTypeBackup" },
  { key: "activityTypeCleanup" },
  { key: "activityTypeDelete" },
  { key: "activityTypeExport" },
  { key: "activityTypeImport" },
  { key: "activityTypeReset" },
  { key: "activityTypeRestore" },
  { key: "activityTypeRule" }
];
