export const appShellLocalization = [
  { selector: "title", target: "text", key: "pageTitle" },
  { selector: ".brand .eyebrow", target: "text", key: "brandName" },
  { selector: ".brand h1", target: "text", key: "appHeading" },
  { selector: ".stats-grid", target: "aria-label", key: "vaultStatsLabel" },
  { selector: ".stats-grid .stat:nth-child(1) p", target: "text", key: "statRecordsLabel" },
  { selector: ".stats-grid .stat:nth-child(2) p", target: "text", key: "statDomainsLabel" },
  { selector: "#stat-newest", target: "text", key: "statNewestEmpty" },
  { selector: ".stats-grid .stat:nth-child(3) p", target: "text", key: "statNewestLabel" },
  { selector: "#stat-backup", target: "text", key: "statBackupEmpty" },
  { selector: ".stats-grid .stat:nth-child(4) p", target: "text", key: "statBackupLabel" },
  { selector: ".tabs", target: "aria-label", key: "sectionsLabel" },
  { selector: '.tab[data-tab="history"]', target: "text", key: "tabHistory" },
  { selector: '.tab[data-tab="quick"]', target: "text", key: "tabQuickOpen" },
  { selector: '.tab[data-tab="backup"]', target: "text", key: "tabBackup" },
  { selector: '.tab[data-tab="rules"]', target: "text", key: "tabRules" },
  { selector: '.tab[data-tab="settings"]', target: "text", key: "tabSettings" },
  { selector: "#status", target: "text", key: "statusReady" },
  { selector: "#tab-history .search-panel", target: "aria-label", key: "historySearchLabel" },
  { selector: ".query-wrap span", target: "text", key: "searchHistoryLabel" },
  { selector: "#query", target: "placeholder", key: "searchQueryPlaceholder" },
  { selector: "#search", target: "text", key: "buttonSearch" },
  { selector: "#clear-search", target: "text", key: "buttonClear" },
  { selector: ".date-shortcuts", target: "aria-label", key: "dateShortcutsLabel" },
  { selector: '[data-date-shortcut="today"]', target: "text", key: "dateToday" },
  { selector: '[data-date-shortcut="yesterday"]', target: "text", key: "dateYesterday" },
  { selector: '[data-date-shortcut="last7"]', target: "text", key: "dateLast7" },
  { selector: '[data-date-shortcut="last30"]', target: "text", key: "dateLast30" },
  { selector: '[data-date-shortcut="all"]', target: "text", key: "dateAllDates" },
  { selector: ".saved-search-line", target: "aria-label", key: "savedSearchesLabel" },
  { selector: "#saved-searches", target: "aria-label", key: "savedSearchesLabel" },
  { selector: '#saved-searches option[value=""]', target: "text", key: "savedSearchesOption" },
  { selector: "#apply-saved-search", target: "text", key: "buttonApply" },
  { selector: "#save-search", target: "text", key: "buttonSaveSearch" },
  { selector: "#delete-saved-search", target: "text", key: "buttonDelete" },
  { selector: ".advanced summary", target: "text", key: "filtersAndSyntax" },
  { selector: ".filters label:nth-child(1)", target: "label-text", key: "filterDay" },
  { selector: ".filters label:nth-child(2)", target: "label-text", key: "filterAfter" },
  { selector: ".filters label:nth-child(3)", target: "label-text", key: "filterBefore" },
  { selector: ".filters label:nth-child(4)", target: "label-text", key: "filterLimit" },
  { selector: ".filters label:nth-child(5)", target: "label-text", key: "filterSort" },
  { selector: '#sort-order option[value="newest"]', target: "text", key: "sortNewestFirst" },
  { selector: '#sort-order option[value="oldest"]', target: "text", key: "sortOldestFirst" },
  { selector: ".advanced .hint", target: "html", key: "syntaxHintHtml" },
  { selector: ".bulkbar", target: "aria-label", key: "bulkActionsLabel" },
  { selector: "#result-count", target: "text", key: "resultCountEmpty" },
  { selector: "#selected-count", target: "text", key: "selectedCountEmpty" },
  { selector: "#select-visible", target: "text", key: "buttonSelectVisible" },
  { selector: "#invert-visible", target: "text", key: "buttonInvertVisible" },
  { selector: "#select-filtered", target: "text", key: "buttonSelectAllResults" },
  { selector: "#load-more", target: "text", key: "buttonLoadMore" },
  { selector: "#load-all", target: "text", key: "buttonShowAll" },
  { selector: "#jump-results-top", target: "text", key: "buttonTop" },
  { selector: "#jump-results-top", target: "aria-label", key: "jumpFirstResultLabel" },
  { selector: "#jump-results-bottom", target: "text", key: "buttonBottom" },
  { selector: "#jump-results-bottom", target: "aria-label", key: "jumpLastResultLabel" },
  { selector: "#clear-selection", target: "text", key: "buttonClear" },
  { selector: "#open-selected", target: "text", key: "buttonOpenSelected" },
  { selector: "#undo-delete", target: "text", key: "buttonUndo" },
  { selector: ".bulk-more summary", target: "text", key: "buttonMore" },
  { selector: "#export-results", target: "text", key: "buttonExportResults" },
  { selector: "#export-results-csv", target: "text", key: "buttonCsvResults" },
  { selector: "#export-results-html", target: "text", key: "buttonHtmlResults" },
  { selector: "#delete-results", target: "text", key: "buttonDeleteResultsVault" },
  { selector: "#delete-results-chrome", target: "text", key: "buttonDeleteResultsChrome" },
  { selector: "#copy-selected", target: "text", key: "buttonCopyUrls" },
  { selector: "#export-selected", target: "text", key: "buttonExportJson" },
  { selector: "#export-selected-csv", target: "text", key: "buttonExportCsv" },
  { selector: "#export-selected-html", target: "text", key: "buttonExportHtml" },
  { selector: "#blacklist-selected", target: "text", key: "buttonBlacklistDomains" },
  { selector: "#delete-vault", target: "text", key: "buttonDeleteFromVault" },
  { selector: "#delete-chrome", target: "text", key: "buttonDeleteUrlsChrome" },
  { selector: "#tab-quick .quick-panel", target: "aria-label", key: "quickOpenLabel" },
  { selector: "#tab-quick .eyebrow", target: "text", key: "tabQuickOpen" },
  { selector: "#tab-quick h2", target: "text", key: "quickOpenHeading" },
  { selector: "#quick-search", target: "text", key: "buttonSearchSources" },
  { selector: "#tab-quick .hint", target: "text", key: "quickOpenHint" },
  { selector: "#tab-backup .backup-panel", target: "aria-label", key: "backupImportLabel" },
  { selector: "#tab-backup > .panel > .section-heading .eyebrow", target: "text", key: "tabBackup" },
  { selector: "#tab-backup > .panel > .section-heading h2", target: "text", key: "backupHeading" },
  { selector: "#sync-chrome", target: "text", key: "buttonSyncChromeHistory" },
  { selector: ".backup-status", target: "aria-label", key: "backupStatusLabel" },
  { selector: "#backup-health", target: "text", key: "backupHealthEmpty" },
  { selector: ".backup-meta div:nth-child(1) dt", target: "text", key: "backupLastLabel" },
  { selector: "#backup-last", target: "text", key: "statBackupEmpty" },
  { selector: ".backup-meta div:nth-child(2) dt", target: "text", key: "backupNextReminderLabel" },
  { selector: "#backup-next", target: "text", key: "backupNextAfterFirst" },
  { selector: ".backup-meta div:nth-child(3) dt", target: "text", key: "backupFormatLabel" },
  { selector: ".backup-meta div:nth-child(4) dt", target: "text", key: "backupRecordsLabel" },
  { selector: ".backup-meta div:nth-child(5) dt", target: "text", key: "backupSizeLabel" },
  { selector: ".backup-meta div:nth-child(6) dt", target: "text", key: "backupSelfTestLabel" },
  { selector: ".backup-meta div:nth-child(7) dt", target: "text", key: "backupConfidenceLabel" },
  { selector: "#backup-confidence", target: "text", key: "backupConfidenceMissing" },
  { selector: ".backup-meta div:nth-child(8) dt", target: "text", key: "backupChecksumLabel" },
  { selector: "#backup-checksum", target: "text", key: "backupChecksumUnavailable" },
  { selector: ".archive-status", target: "aria-label", key: "archiveRecorderHealthLabel" },
  { selector: "#archive-health", target: "text", key: "archiveSyncNotRun" },
  { selector: ".archive-status .backup-meta div:nth-child(1) dt", target: "text", key: "archiveStartupLabel" },
  { selector: "#archive-startup", target: "text", key: "archiveNotRecorded" },
  { selector: ".archive-status .backup-meta div:nth-child(2) dt", target: "text", key: "archiveChromeSyncLabel" },
  { selector: "#archive-sync", target: "text", key: "archiveNotSynced" },
  { selector: ".archive-status .backup-meta div:nth-child(3) dt", target: "text", key: "archiveLiveCaptureLabel" },
  { selector: "#archive-capture", target: "text", key: "archiveWaitingForVisit" },
  { selector: ".archive-status .backup-meta div:nth-child(4) dt", target: "text", key: "archiveStorageCheckLabel" },
  { selector: "#archive-storage", target: "text", key: "archiveNotChecked" },
  { selector: ".archive-status .backup-meta div:nth-child(5) dt", target: "text", key: "archiveVaultCheckLabel" },
  { selector: "#archive-vault", target: "text", key: "archiveVaultEmpty" },
  { selector: ".archive-status .backup-meta div:nth-child(6) dt", target: "text", key: "archiveTombstonesLabel" },
  { selector: "#archive-tombstones", target: "text", key: "archiveNoTombstones" },
  { selector: ".archive-insights", target: "aria-label", key: "archiveInsightsLabel" },
  { selector: ".archive-insights .eyebrow", target: "text", key: "insightsEyebrow" },
  { selector: ".archive-insights h3", target: "text", key: "archiveOverviewHeading" },
  { selector: ".archive-insights .backup-meta div:nth-child(1) dt", target: "text", key: "topDomainsLabel" },
  { selector: "#archive-top-domains", target: "text", key: "noDomainsYet" },
  { selector: ".archive-insights .backup-meta div:nth-child(2) dt", target: "text", key: "busiestDayLabel" },
  { selector: "#archive-busiest-day", target: "text", key: "noVisitsYet" },
  { selector: ".archive-insights .backup-meta div:nth-child(3) dt", target: "text", key: "activeDaysLabel" },
  { selector: "#archive-active-days", target: "text", key: "noActiveDaysYet" },
  { selector: ".archive-insights .backup-meta div:nth-child(4) dt", target: "text", key: "dateRangeLabel" },
  { selector: "#archive-date-range", target: "text", key: "noVisitsYet" },
  { selector: ".activity-status", target: "aria-label", key: "recentActivityLabel" },
  { selector: ".activity-status .eyebrow", target: "text", key: "activityEyebrow" },
  { selector: ".activity-status h3", target: "text", key: "recentChangesHeading" },
  { selector: ".activity-item.is-empty", target: "text", key: "noActivityLogged" },
  { selector: "#export-json", target: "text", key: "buttonExportJson" },
  { selector: "#export-csv", target: "text", key: "buttonExportCsv" },
  { selector: "#export-html", target: "text", key: "buttonExportHtml" },
  { selector: 'label[for="import-archive"]', target: "text", key: "buttonImportArchive" },
  { selector: "#reset-vault", target: "text", key: "buttonResetVault" },
  { selector: "#import-preview", target: "aria-label", key: "importPreviewLabel" },
  { selector: "#import-preview .eyebrow", target: "text", key: "importPreviewEyebrow" },
  { selector: "#import-preview-title", target: "text", key: "importPreviewHeading" },
  { selector: "#cancel-import", target: "text", key: "buttonCancel" },
  { selector: "#import-health", target: "text", key: "archiveNotChecked" },
  { selector: ".preview-stat:nth-child(1) p", target: "text", key: "validRowsLabel" },
  { selector: ".preview-stat:nth-child(2) p", target: "text", key: "newVisitsLabel" },
  { selector: ".preview-stat:nth-child(3) p", target: "text", key: "alreadySavedLabel" },
  { selector: ".preview-stat:nth-child(4) p", target: "text", key: "fileDuplicatesLabel" },
  { selector: "#confirm-import", target: "text", key: "buttonImportNow" },
  { selector: "#tab-rules .rules-panel", target: "aria-label", key: "domainRulesLabel" },
  { selector: "#tab-rules > .panel > .section-heading .eyebrow", target: "text", key: "tabRules" },
  { selector: "#tab-rules h2", target: "text", key: "rulesHeading" },
  { selector: "#rule-domain", target: "placeholder", key: "ruleDomainPlaceholder" },
  { selector: "#rule-category", target: "placeholder", key: "ruleCategoryPlaceholder" },
  { selector: "#add-category", target: "text", key: "buttonCategorize" },
  { selector: "#add-blacklist", target: "text", key: "buttonBlacklist" },
  { selector: "#add-whitelist", target: "text", key: "buttonWhitelist" },
  { selector: ".retention-cleanup:nth-of-type(1)", target: "aria-label", key: "retentionCleanupLabel" },
  { selector: ".retention-cleanup:nth-of-type(1) .eyebrow", target: "text", key: "retentionEyebrow" },
  { selector: ".retention-cleanup:nth-of-type(1) h3", target: "text", key: "retentionHeading" },
  { selector: ".retention-cleanup:nth-of-type(1) label", target: "label-text", key: "retentionDaysLabel" },
  { selector: "#preview-retention", target: "text", key: "buttonPreview" },
  { selector: "#cleanup-retention", target: "text", key: "buttonCleanUp" },
  { selector: ".retention-cleanup:nth-of-type(1) .hint", target: "text", key: "retentionHint" },
  { selector: ".retention-cleanup:nth-of-type(2)", target: "aria-label", key: "duplicateCleanupLabel" },
  { selector: ".retention-cleanup:nth-of-type(2) .eyebrow", target: "text", key: "duplicatesEyebrow" },
  { selector: ".retention-cleanup:nth-of-type(2) h3", target: "text", key: "duplicatesHeading" },
  { selector: ".retention-cleanup:nth-of-type(2) .hint", target: "text", key: "duplicatesHint" },
  { selector: "#preview-duplicates", target: "text", key: "buttonPreview" },
  { selector: "#cleanup-duplicates", target: "text", key: "buttonCleanUp" },
  { selector: "#tab-settings .settings-panel", target: "aria-label", key: "displaySettingsLabel" },
  { selector: "#tab-settings .settings-panel .eyebrow", target: "text", key: "tabSettings" },
  { selector: "#tab-settings .settings-panel h2", target: "text", key: "settingsHeading" },
  { selector: "#save-preferences", target: "text", key: "buttonSaveSettings" },
  { selector: '.settings-grid label:nth-child(1)', target: "label-text", key: "themeLabel" },
  { selector: '#pref-theme option[value="system"]', target: "text", key: "themeSystem" },
  { selector: '#pref-theme option[value="light"]', target: "text", key: "themeLight" },
  { selector: '#pref-theme option[value="dark"]', target: "text", key: "themeDark" },
  { selector: '.settings-grid label:nth-child(2)', target: "label-text", key: "accentLabel" },
  { selector: '#pref-accent option[value="teal"]', target: "text", key: "accentTeal" },
  { selector: '#pref-accent option[value="blue"]', target: "text", key: "accentBlue" },
  { selector: '#pref-accent option[value="green"]', target: "text", key: "accentGreen" },
  { selector: '#pref-accent option[value="purple"]', target: "text", key: "accentPurple" },
  { selector: '#pref-accent option[value="slate"]', target: "text", key: "accentSlate" },
  { selector: '.settings-grid label:nth-child(3)', target: "label-text", key: "contrastLabel" },
  { selector: '#pref-contrast option[value="standard"]', target: "text", key: "standardOption" },
  { selector: '#pref-contrast option[value="high"]', target: "text", key: "highContrastOption" },
  { selector: '.settings-grid label:nth-child(4)', target: "label-text", key: "textSizeLabel" },
  { selector: '#pref-text-size option[value="standard"]', target: "text", key: "standardOption" },
  { selector: '#pref-text-size option[value="large"]', target: "text", key: "largeOption" },
  { selector: '.settings-grid label:nth-child(5)', target: "label-text", key: "dateDisplayLabel" },
  { selector: '#pref-date-format option[value="system"]', target: "text", key: "systemLocaleOption" },
  { selector: '#pref-date-format option[value="iso"]', target: "text", key: "isoDateOption" },
  { selector: '#pref-date-format option[value="dmy"]', target: "text", key: "dayMonthYearDateOption" },
  { selector: '#pref-date-format option[value="mdy"]', target: "text", key: "monthDayYearDateOption" },
  { selector: '#pref-date-format option[value="ymd"]', target: "text", key: "yearMonthDayDateOption" },
  { selector: '.settings-grid label:nth-child(6)', target: "label-text", key: "defaultResultLimitLabel" },
  { selector: '.settings-grid label:nth-child(7)', target: "label-text", key: "backupReminderDaysLabel" },
  { selector: '.settings-grid label:nth-child(8)', target: "label-text", key: "saveFilesLabel" },
  { selector: '#pref-backup-save-mode option[value="downloads"]', target: "text", key: "downloadsFolderOption" },
  { selector: '#pref-backup-save-mode option[value="ask"]', target: "text", key: "askEveryExportOption" },
  { selector: '.settings-grid label:nth-child(9)', target: "label-text", key: "backupFilenamePrefixLabel" },
  { selector: '.settings-grid label:nth-child(10)', target: "label-text", key: "backupFilenameTemplateLabel" },
  { selector: "#pref-backup-template", target: "placeholder", key: "backupFilenameTemplatePlaceholder" },
  { selector: ".trust-panel", target: "aria-label", key: "trustLimitsLabel" },
  { selector: ".trust-panel .eyebrow", target: "text", key: "trustEyebrow" },
  { selector: ".trust-panel h2", target: "text", key: "trustHeading" },
  { selector: "#open-native-history", target: "text", key: "buttonOpenChromeHistory" },
  { selector: ".trust-list div:nth-child(1) dt", target: "text", key: "permissionHistoryLabel" },
  { selector: ".trust-list div:nth-child(1) dd", target: "text", key: "permissionHistoryDescription" },
  { selector: ".trust-list div:nth-child(2) dt", target: "text", key: "permissionBrowserSourcesLabel" },
  { selector: ".trust-list div:nth-child(2) dd", target: "text", key: "permissionBrowserSourcesDescription" },
  { selector: ".trust-list div:nth-child(3) dt", target: "text", key: "permissionStorageLabel" },
  { selector: ".trust-list div:nth-child(3) dd", target: "text", key: "permissionStorageDescription" },
  { selector: ".trust-list div:nth-child(4) dt", target: "text", key: "permissionNetworkLabel" },
  { selector: ".trust-list div:nth-child(4) dd", target: "text", key: "permissionNetworkDescription" },
  { selector: ".limit-list", target: "aria-label", key: "productLimitsLabel" },
  { selector: ".limit-list li:nth-child(1) strong", target: "text", key: "oldHistoryLimitLabel" },
  { selector: ".limit-list li:nth-child(1) span", target: "text", key: "oldHistoryLimitDescription" },
  { selector: ".limit-list li:nth-child(2) strong", target: "text", key: "nativeHistoryLimitLabel" },
  { selector: ".limit-list li:nth-child(2) span", target: "text", key: "nativeHistoryLimitDescription" },
  { selector: ".limit-list li:nth-child(3) strong", target: "text", key: "deviceHistoryLimitLabel" },
  { selector: ".limit-list li:nth-child(3) span", target: "text", key: "deviceHistoryLimitDescription" },
  { selector: "#result-template .check-wrap span", target: "text", key: "selectLabel" },
  { selector: "#quick-result-template .quick-copy", target: "text", key: "buttonCopy" },
  { selector: "#quick-result-template .quick-background", target: "text", key: "buttonOpenBackground" },
  { selector: "#quick-result-template .quick-action", target: "text", key: "buttonOpen" }
];
